### ISSUE TITLE
Add readme 

### ISSUE THREAD

**Issue by alok760** [nk521/hackathonti.me#2]
Add readme with - 
* [x] idea
* [x] work already done 
* [x] contribution guide 
* [x] work in progress 
* [ ] Screenshots 
* [x] setup guide 
* [x] future plans

**Comment by grlwholifts** [comment]
Hi @alok760, i would like to take this up!

**Comment by nk521** [comment]
Assigned to @ruchikabgosain

**Comment by ruchikabgosain** [comment]
Added a raw version : [ https://github.com/nk521/hackathonti.me/commit/25cc3188b512b3b90b40857e55801b4bfe62264a ]

**Comment by grlwholifts** [comment]
Added README! Let me know if there are any changes.

**Comment by nk521** [comment]
Sounds good. Thanks @ruchikabgosain :D. I'll add screenshots after some time.
https://github.com/nk521/hackathontime/commit/af3970330fc3ca321d68455f8cd7a9980d95f2cb

closing this issue for now
